# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('codeID', models.IntegerField(primary_key=True, serialize=False)),
                ('codeName', models.CharField(max_length=255)),
                ('displayOrder', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'com_code',
            },
        ),
        migrations.CreateModel(
            name='codeGroup',
            fields=[
                ('codeGroupID', models.IntegerField(primary_key=True, serialize=False)),
                ('codeGroupName', models.CharField(max_length=255, unique=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'com_codeGroup',
                'get_latest_by': 'codeGroupName',
            },
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('petID', models.AutoField(primary_key=True, serialize=False)),
                ('petName', models.CharField(max_length=255)),
                ('petDescription', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('petCategory', models.ForeignKey(db_column=b'petCategory', on_delete=django.db.models.deletion.CASCADE, to='Catalog.code')),
            ],
            options={
                'db_table': 'pet_pet',
            },
        ),
        migrations.CreateModel(
            name='petDetails',
            fields=[
                ('petDetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('petAge', models.FloatField()),
                ('petColor', models.CharField(max_length=255)),
                ('petHeight', models.FloatField()),
                ('petWeight', models.FloatField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('petID', models.ForeignKey(db_column=b'petID', on_delete=django.db.models.deletion.CASCADE, to='Catalog.pet')),
                ('petType', models.ForeignKey(db_column=b'petType', on_delete=django.db.models.deletion.CASCADE, to='Catalog.code')),
            ],
            options={
                'db_table': 'pet_petDetails',
            },
        ),
        migrations.AddField(
            model_name='code',
            name='codeGroup',
            field=models.ForeignKey(db_column=b'codeGroupID', on_delete=django.db.models.deletion.CASCADE, related_name='code_codeGroupID', to='Catalog.codeGroup'),
        ),
    ]
